safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /
url: http://diurnal.st

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: [smart]

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

# Google Analytics
googleAnalytics: UA-38025103-1

# Disqus
disqusShortName: diurnalist

# Typekit
#typekit: yzr7skt #dev
typekit: rzi0pwr #prod